name: GuildQuest
version: '1.4'
main: ua.striker.guildquest.GuildQuest
api-version: '1.21'
depend: [PlaceholderAPI, Vault]
commands:
  guildquest:
    description: Головна команда Гільдії Пригод
    aliases: [gq, guild]