# ==========================================
#       GuildQuest - Налаштування
# ==========================================

# Комісія при створенні квесту у відсотках
# Це анти-абуз механіка, яка також виводить зайві гроші з економіки сервера
creation-commission-percent: 5.0

# Налаштування очок Гільдії за виконання замовлень
# Ціна вказується за 1 одиницю предмета
points:
  default-points: 1
  items:
    DIAMOND: 50
    EMERALD: 40
    NETHERITE_INGOT: 100
    IRON_INGOT: 10
    GOLD_INGOT: 15
    COBBLESTONE: 0
    DIRT: 0
    
    # ==========================================
#       Система Рангів
# ==========================================

rank-system:
  # Якщо true - для підвищення рангу потрібні і очки, і унікальні замовники.
  # Якщо false - ранг підвищуватиметься ТІЛЬКИ за кількість очок (ідеально для тестів).
  require-unique-clients: true